apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: jmeter
  name: jmeter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      containers:
      - image: systemdevformations/jmeter-k8s:latest
        command: [ "/usr/bin/tail" ]  # added
        args: [ "-f", "/dev/null" ]   # added
        imagePullPolicy: Always
        name: jmeter-k8s

